# Change the default prefix key from 'Ctrl+b' to 'Ctrl+a'
# This is a common preference as Ctrl+a is often easier to reach
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

setw -g mode-keys vi

# Start numbering windows and panes from 1 instead of 0
# Makes it easier to select windows using keyboard number keys
set -g base-index 1
set-window-option -g pane-base-index 1
set-window-option -g renumber-windows on # Renumber windows automatically when one is closed

# Enable mouse support to resize panes, select windows/panes, and scroll
set-option -g mouse on

# Set terminal title
set-option -g set-titles on
set-option -g set-titles-string "#S:#I:#W - \"#T\""

# Enable 256 colors support
# Set 24-bit true color support
set -g terminal-features ",xterm-kitty:RGB"

set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*256col*:Tc"
set -as terminal-features ",*:RGB"

# Rebind pane navigation to vim keys (h,j,k,l) after the prefix
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Rebind pane splitting to use more intuitive keys (e.g., | for vertical split, - for horizontal)
bind q split-window -h -c '#{pane_current_path}' # Split vertically
bind w split-window -v -c '#{pane_current_path}' # Split horizontally
unbind '"' # Unbind default horizontal split key
unbind % # Unbind default vertical split key

# Create new windows in the current pane's path
bind c new-window -c '#{pane_current_path}'

# New Session
bind C command-prompt -p "Session name:" "new-session -A -s '%%'"

# Paste Buffer
bind p choose-buffer # choose which buffer to paste from


# Reload the configuration file with Prefix + r
bind r source-file ~/.tmux.conf \; display-message "Config reloaded!"


# TMUX RESSURECT SETTINGS
# for vim
set -g @resurrect-strategy-vim 'session'
# for neovim
set -g @resurrect-strategy-nvim 'session'
set -g @resurrect-capture-pane-contents 'on'

# CATPUCCIN FONT SENTINGS
set -g @catppuccin_flavour 'mocha'
set -g @catppuccin_window_status_icon_enable "no"
set -g @catppuccin_icon_window_last "󰖰"
set -g @catppuccin_icon_window_current "󰖯"
set -g @catppuccin_icon_window_zoom "󰁌"

# TMUX POWERLINE
set -g @tmux_power_theme 'moon'   # or 'forest', 'violet', 'sky', 'snow', 'redwine', 'moon', 'everforest'

# TMUX Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-open'
set -g @plugin 'tmux-plugins/tmux-logging'
set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'tmux-plugins/tmux-copycat'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'wfxr/tmux-power'



# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/plugins/tpm/tpm
